<?php

namespace RhBundle\Repository;

/**
 * CategorieEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
