<?php

namespace RhBundle\Repository;

/**
 * EtatEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
