<?php

namespace RhBundle\Repository;

/**
 * EtatCongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatCongeRepository extends \Doctrine\ORM\EntityRepository
{
}
