<?php

namespace RhBundle\Repository;

/**
 * EtatFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
