<?php

namespace RhBundle\Repository;

/**
 * MetierEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
