<?php

namespace RhBundle\Repository;

/**
 * NationaliteConjointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationaliteConjointRepository extends \Doctrine\ORM\EntityRepository
{
}
