<?php

namespace RhBundle\Repository;

/**
 * NationaliteEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationaliteEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
