<?php

namespace RhBundle\Repository;

/**
 * NationaliteEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationaliteEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
