<?php

namespace RhBundle\Repository;

/**
 * OffreFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
