<?php

namespace RhBundle\Repository;

/**
 * StatutEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
