<?php

namespace RhBundle\Repository;

/**
 * TypeNominationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeNominationRepository extends \Doctrine\ORM\EntityRepository
{
}
