<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActions(\AppBundle\Entity\Formation $formation)
    {
        $qb=$this->createQueryBuilder('a')
            ->select('a.id','a.nomAction','a.coutAction','f.id as idfor'
            )
            ->innerJoin('AppBundle:Formation', 'f', Join::WITH, 'f.id = a.formation')
            //->where('c.tag != 1')
            ->where('f.id = :formationId')
            ->setParameter('formationId', $formation->getId())
        ;

        try {
            return ($qb ->getQuery()->getResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getAction(\AppBundle\Entity\Action $action)
    {
        $qb=$this->createQueryBuilder('a')
            ->select('a.id','a.nomAction','a.coutAction','f.id as idfor'
            )
            ->innerJoin('AppBundle:Formation', 'f', Join::WITH, 'f.id = a.formation')
            //->where('c.tag != 1')
            ->where('a.id = :actionId')
            ->setParameter('actionId', $action->getId())
        ;

        try {
            return ($qb ->getQuery()->getOneOrNullResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
