<?php

namespace AppBundle\Repository;

/**
 * CompetenceEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
