<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findContacts()
    {
        $qb=$this->createQueryBuilder('c')
            ->select('c.id','c.nomcontact','c.prenomcontact','c.sexecontact','c.emailcontact',
            'c.telephone','e.prenom')
            ->innerJoin('AppBundle:Employe', 'e', Join::WITH, 'e.id = c.employe')
           /* ->where('c.tag != 1')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())*/
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
