<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * DirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDirections()
    {
        $qb=$this->createQueryBuilder('di');
        $qb
            ->select('di.id','di.nomdirection','di.tag')
            ->where('di.tag != 1')

        ;
        return $qb ->getQuery()->getResult();
    }
    public function getDepartements()
    {
        $qb=$this->createQueryBuilder('d')
            ->select('de.id','d.nomdirection','de.nomdepartement')
            ->innerJoin('AppBundle:Departement', 'de', Join::WITH, 'd.id = de.direction')
            ->andwhere('de.tag != 1')
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
