<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;


/**
 * EmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findConjoints($id)
    {
        $qb=$this->createQueryBuilder('e');
        $qb
            ->select('c')
            ->from('AppBundle:Conjoint','c')
            ->where('c.tag != 1')
            ->andWhere('c.employe = :id')
            ->setParameter('id', $id);
        return $qb;
        ;

    }
    public function getEmployes()
    {
        $qb=$this->createQueryBuilder('e');
        $qb
            ->select('e.id','e.nom','e.prenom','e.matricule','e.tag')
            ->where('e.tag != 1')
            ;
        return $qb ->getQuery()->getResult();
    }
    public function findEmployeBySexe()
    {
        $qb=$this->createQueryBuilder('e')
        ->select('count(e.id) as nbre','e.sexe','e.tag')
        ->where('e.tag !=1')
        //->innerJoin('AppBundle:EtatFormation', 'ef', Join::WITH, 'ef.id = f.etatformation')
        ->groupBy('e.sexe')
        
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function findEmployesByCategorie()
    {
        $qb=$this->createQueryBuilder('e')
        ->select('count(e.id) as nbrem','ce.nomcategorieemploye')
        ->innerJoin('AppBundle:CategorieEmploye', 'ce', Join::WITH, 'ce.id = e.categorieemploye')
        ->groupBy('ce.nomcategorieemploye')
        
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function findEmployesByService()
    {
        $qb=$this->createQueryBuilder('e')
        ->select('count(e.id) as nbrser','s.nomservice')
        ->innerJoin('AppBundle:Service', 's', Join::WITH, 's.id = e.service')
        ->groupBy('s.nomservice')
        
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
