<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * EtatEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatEmployeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEtats(\AppBundle\Entity\Employe $employe)
    {
        $qb=$this->createQueryBuilder('et')
            ->innerJoin('AppBundle:EtatEmploye', 'ee', Join::WITH, 'et.id = ee.etat')
            ->innerJoin('AppBundle:Employe', 'e', Join::WITH, 'ee.employe = e.id')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
