<?php

namespace AppBundle\Repository;

/**
 * EvaluationEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
