<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvaluations()
    {
        $qb=$this->createQueryBuilder('e')
            ->select('e.id','e.nomEvaluation','e.datedebut','e.datefin','e.description','te.nomTypeEvaluation')
            ->innerJoin('AppBundle:TypeEvaluation', 'te', Join::WITH, 'te.id = e.typeevaluation')
           /* ->where('c.tag != 1')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())*/
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getEvaluations(\AppBundle\Entity\Evaluation $evaluation)
    {
        $qb=$this->createQueryBuilder('e')
            ->select('e.id','e.nomEvaluation','e.datedebut','e.datefin','e.description','te.nomTypeEvaluation')
            ->innerJoin('AppBundle:TypeEvaluation', 'te', Join::WITH, 'te.id = e.typeevaluation')
           //->where('c.tag != 1')
            ->where('e.id = :evaluationId')
            ->setParameter('evaluationId', $evaluation->getId())
        ;

        try {
            return $qb ->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
