<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * FonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFonctions()
    {
        $qb=$this->createQueryBuilder('f');
        $qb
            ->select('f.id','f.nomfonction','f.tag')
            ->where('f.tag != 1')

        ;
        return $qb ->getQuery()->getResult();
    }
    public function getFonctions(\AppBundle\Entity\Employe $employe)
    {
        $qb=$this->createQueryBuilder('n')
            ->select('n.id','n.nomfonction','fe.datedebutfonction','fe.tag','fe.datefin')
            ->innerJoin('AppBundle:FonctionEmploye', 'fe', Join::WITH, 'n.id = fe.fonction')
            ->innerJoin('AppBundle:Employe', 'e', Join::WITH, 'fe.employe = e.id')
            //->where('fe.tag != 1')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())
        ;

        try {
            return ($qb ->getQuery()->getResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getFonction1(\AppBundle\Entity\Employe $employe)
    {
        $qb=$this->createQueryBuilder('n')

            ->select('n.id','e.id as idemp','n.nomfonction','fe.datedebutfonction','fe.tag','fe.datefin','fe.id as idfemp')
            ->innerJoin('AppBundle:FonctionEmploye', 'fe', Join::WITH, 'n.id = fe.fonction')
            ->innerJoin('AppBundle:Employe', 'e', Join::WITH, 'fe.employe = e.id')
            ->orderBy('fe.id', 'DESC')
            ->setMaxResults(1)
            ->where('fe.tag != 1')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())


        ;

        try {
            return ($qb ->getQuery()->getSingleResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function findEmployeByFonction()
    {
        $qb=$this->createQueryBuilder('f')
            ->select('count(e.id) as nbrfonc','f.nomfonction')
            ->innerJoin('AppBundle:FonctionEmploye', 'fe', Join::WITH, 'f.id = fe.fonction')
            ->innerJoin('AppBundle:Employe', 'e', Join::WITH, 'fe.employe = e.id')
            ->where('fe.tag != 1')
            //->andWhere('e.id = :employeId')
            //->setParameter('employeId', $employe->getId())
            ->groupBy('f.nomfonction')
        ;
        try {
            return ($qb ->getQuery()->getResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
