<?php

namespace AppBundle\Repository;

/**
 * FonctionEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
