<?php

namespace AppBundle\Repository;

/**
 * FormationEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
