<?php

namespace AppBundle\Repository;

/**
 * FormateurRetenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormateurRetenuRepository extends \Doctrine\ORM\EntityRepository
{
}
