<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFormations()
    {
        $qb=$this->createQueryBuilder('f')
            ->select('f.id','f.nomFormation','f.datedebutformation','f.datefinformation','f.lieuFomation','tf.nomtypeformation','ef.nometatformation')
            ->innerJoin('AppBundle:TypeFormation', 'tf', Join::WITH, 'tf.id = f.typeformation')
            ->innerJoin('AppBundle:EtatFormation', 'ef', Join::WITH, 'ef.id = f.etatformation')
           /* ->where('c.tag != 1')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())*/
        ;
        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getFormations(\AppBundle\Entity\Formation $formation)
    {
        $qb=$this->createQueryBuilder('f')
        ->select('f.id','f.nomFormation','f.datedebutformation','f.datefinformation','f.lieuFomation','tf.nomtypeformation','ef.nometatformation')
        ->innerJoin('AppBundle:TypeFormation', 'tf', Join::WITH, 'tf.id = f.typeformation')
        ->innerJoin('AppBundle:EtatFormation', 'ef', Join::WITH, 'ef.id = f.etatformation')
           //->where('c.tag != 1')
        ->where('f.id = :formationId')
        ->setParameter('formationId', $formation->getId())
        ;

        try {
            return $qb ->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getFormationsStats()
    {
        $qb=$this->createQueryBuilder('f')
        ->select('count(f.id) as nbrfor','tf.nomtypeformation')
        ->innerJoin('AppBundle:TypeFormation', 'tf', Join::WITH, 'tf.id = f.typeformation')
        ->groupBy('tf.nomtypeformation')
        
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getFormationsStatsetat()
    {
        $qb=$this->createQueryBuilder('f')
        ->select('count(f.id) as nbretat','ef.nometatformation')
        ->innerJoin('AppBundle:EtatFormation', 'ef', Join::WITH, 'ef.id = f.etatformation')
        ->groupBy('ef.nometatformation')
        
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function TrouverFormations(\AppBundle\Entity\Programme $programme)
    {
        $qb=$this->createQueryBuilder('f')
            ->select('f.id as idfor','f.nomFormation','p.id')
            ->innerJoin('AppBundle:Programme', 'p', Join::WITH, 'f.id = p.formation')
            //->where('c.tag != 1')
            ->where('f.id = :programmeId')
            ->setParameter('programmeId', $programme->getId())
        ;

        try {
            return ($qb ->getQuery()->getSingleResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
