<?php

namespace AppBundle\Repository;

/**
 * GrappeFamilialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrappeFamilialeRepository extends \Doctrine\ORM\EntityRepository
{
}
