<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * MaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMateriels(\AppBundle\Entity\Formation $formation)
    {
        $qb=$this->createQueryBuilder('m')
            ->select('m.id','m.nomMateriel','m.quantite','f.id as idfor'
            )
            ->innerJoin('AppBundle:Formation', 'f', Join::WITH, 'f.id = m.formation')
            //->where('c.tag != 1')
            ->where('f.id = :formationId')
            ->setParameter('formationId', $formation->getId())
        ;

        try {
            return ($qb ->getQuery()->getResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getMateriel(\AppBundle\Entity\Materiel $materiel)
    {
        $qb=$this->createQueryBuilder('m')
            ->select('m.id','m.nomMateriel','m.quantite','f.id as idfor'
            )
            ->innerJoin('AppBundle:Formation', 'f', Join::WITH, 'f.id = m.formation')
            //->where('c.tag != 1')
            ->where('m.id = :materielId')
            ->setParameter('materielId', $materiel->getId())
        ;

        try {
            return ($qb ->getQuery()->getOneOrNullResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
