<?php

namespace AppBundle\Repository;

/**
 * NationnaliteEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationnaliteEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
