<?php

namespace AppBundle\Repository;

/**
 * NationnaliteEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationnaliteEmployeRepository extends \Doctrine\ORM\EntityRepository
{

}
