<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * OffreFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreFormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOffreFormations(\AppBundle\Entity\Formation $formation)
    {
        $qb=$this->createQueryBuilder('o')
            ->select('o.id','o.intitule','o.budget','o.theme','o.datedebutoffre','o.datefinoffre','f.id as idfor'
            )
            ->innerJoin('AppBundle:Formation', 'f', Join::WITH, 'f.id = o.formation')
            //->where('c.tag != 1')
            ->where('f.id = :formationId')
            ->setParameter('formationId', $formation->getId())
        ;

        try {
            return ($qb ->getQuery()->getResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    public function getOffreFormation(\AppBundle\Entity\OffreFormation $offreformation)
    {
        $qb=$this->createQueryBuilder('o')
            ->select('o.id','o.intitule','o.budget','o.theme','o.datedebutoffre','o.datefinoffre',
            'f.id as idfor'
            )
            ->innerJoin('AppBundle:Formation', 'f', Join::WITH, 'f.id = o.formation')
            //->where('c.tag != 1')
            ->where('o.id = :offreformationId')
            ->setParameter('offreformationId', $offreformation->getId())
        ;

        try {
            return ($qb ->getQuery()->getOneOrNullResult());
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
