<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findServices()
    {
        $qb=$this->createQueryBuilder('ss');
        $qb
            ->select('ss.id','ss.nomservice','ss.tag')
            ->where('ss.tag != 1')

        ;
        return $qb ->getQuery()->getResult();
    }
    public function getServices(\AppBundle\Entity\Employe $employe)
    {
        $qb=$this->createQueryBuilder('s')
            ->select('s.id','s.nomservice','s.tag','e.id as idemp')
            ->innerJoin('AppBundle:Employe', 'e', Join::WITH, 's.id = e.service')
            ->andWhere('e.id = :employeId')
            ->setParameter('employeId', $employe->getId())
        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
