<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * StatutEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutEmployeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStatuts()
    {
        $qb=$this->createQueryBuilder('st');
        $qb
            ->select('st.id','st.nomstatutemploye','st.tag')
            ->where('st.tag != 1')
        ;
        return $qb ->getQuery()->getResult();
    }
    public function getStatuts()
    {
        $qb=$this->createQueryBuilder('s')
            ->select('c.id','s.nomstatutemploye','c.nomcategorieemploye','c.tag')
            ->innerJoin('AppBundle:CategorieEmploye', 'c', Join::WITH, 's.id = c.statutemploye')
            ->where('c.tag != 1')

        ;

        try {
            return $qb ->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
