<?php

namespace AppBundle\Repository;

/**
 * TypeContratEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContratEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
