<?php

namespace AppBundle\Repository;

/**
 * TypeEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
