security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_EMPLOYE
        ROLE_ADMIN:       ROLE_AGENTRH
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/employe, role: ROLE_AGENTRH}
        - { path: ^/employe, role: ROLE_ADMIN}
        - { path: ^/formation/edit, role: ROLE_AGENTRH}
        - { path: ^/formation/new, role: ROLE_AGENTRH}
        - { path: ^/formation_show, role: ROLE_AGENTRH}
        - { path: ^/parametrage, role: ROLE_AGENTRH}
        - { path: ^/formateur, role: ROLE_AGENTRH}
        
      