# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    #app.cv_uploader:  
    #    class: AppBundle\FileUploader
    #    arguments: ['%cvs_directory%']
    #app.doctrine_cv_listener:
    #    class: AppBundle\EventListener\CvUploadListener
    #    arguments: ['@app.cv_uploader']
    #   tags:
    #        - { name: doctrine.event_listener, event: prePersist }
    #        - { name: doctrine.event_listener, event: preUpdate }
